local mock = require("mock_socket")

describe("paired sockets exchange bytes", function()
  local a, b = mock.makePair()
  a:settimeout(0); b:settimeout(0)
  a:send("hello")
  local got = b:receive(5)
  assertEq(got, "hello")
end)

describe("receive on empty buffer returns timeout", function()
  local a, b = mock.makePair()
  b:settimeout(0)
  local got, err = b:receive(1)
  assertEq(got, nil)
  assertEq(err, "timeout")
end)

describe("receive returns partial on short buffer", function()
  local a, b = mock.makePair()
  a:settimeout(0); b:settimeout(0)
  a:send("ab")
  local got, err, partial = b:receive(5)
  assertEq(got, nil)
  assertEq(err, "timeout")
  assertEq(partial, "ab")
end)

describe("close on one side surfaces on other", function()
  local a, b = mock.makePair()
  a:settimeout(0); b:settimeout(0)
  a:close()
  local got, err = b:receive(1)
  assertEq(got, nil)
  assertEq(err, "closed")
end)

describe("multiple sends concatenate", function()
  local a, b = mock.makePair()
  a:settimeout(0); b:settimeout(0)
  a:send("foo"); a:send("bar")
  assertEq(b:receive(6), "foobar")
end)
